# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180420_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='immiuser',
            name='activation_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
