# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_immiuser_activation_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immiuser',
            old_name='activation_token',
            new_name='activation_token_a',
        ),
    ]
