# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180422_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='immiuser',
            name='activation_token_b',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
