# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_immiuser_activation_token_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmiDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
